### ISSUE TITLE
Add vector-based filtering for B-grid models

### ISSUE THREAD

**Issue by paigem** [ocean-eddy-cpt/gcm-filters#106]
First off, thanks to the developers for this really great package with excellent documentation!

I would like to apply a vector-based filtering scheme to a B grid model (POP). It looks like the only current implementation of vector filtering is `VECTOR_C_GRID` for models with an Arakawa C grid. 

Would a corresponding `VECTOR_B_GRID` be a desirable feature to add to `gcm_filters`? If so, I'd be happy to take a stab at implementing it!

**Comment by rabernat** [comment]
For context, this would enable filtering of velocity fields on MOM5 and POP grids. I support it 💯 .

**Comment by iangrooms** [comment]
I agree - this would be useful.

**Comment by NoraLoose** [comment]
Hi Paige, nice to see you here!

Having a vector Laplacian on a B-grid would be super useful - thanks for taking this on! :rocket: 
(Griffies' book (2004), the POP manual, and the POP code itself will probably be useful references.)

> For context, this would enable filtering of velocity fields on MOM5 and POP grids.

If we are planning to implement a tripole boundary condition for the B-grid Laplacian, I can probably help with that (if needed). At some point I thought about how to implement the tripole exchanges on a vector grid, and will dig out the relevant code snippet. But I imagine that the boundary condition will be something we will tackle further down the road.

**Comment by paigem** [comment]
Great, it sounds like this is a desired feature so I'll get started! Thanks @NoraLoose for the useful references - I'll start by looking at those references and the vector Laplacian on a  C-grid code to get started. It might take a little time to spin up on all of this, but very keen to contribute! 

Your help with the triple boundary condition, and with the implementation in general, would be greatly appreciated @NoraLoose!
