### ISSUE TITLE
API documentation for filter class methods

### ISSUE THREAD

**Issue by NoraLoose** [ocean-eddy-cpt/gcm-filters#110]
[As part of the JOSS review]( https://github.com/openjournals/joss-reviews/issues/3947#issuecomment-990591734), @callumrollo made a comment regarding our API documentation, which I am reposting here:

> Reading the API documentation, I am unclear on the difference between these two methods of the Filter class:
> 
> apply(self, field_or_dataset, dims):
> """Filter a field or xarray dataset with scalar Laplacian across the
> dimensions specified by dims."""
> 
> apply_to_field(self, field, dims):
> """Filter a field with scalar Laplacian across the dimensions specified by dims."""
> 
> If apply can process a field or dataset, apply_to_field seems superfluous. If they are performing different functions, this could be better explained in their docstrings

@asross would you like to handle this issue? (I'm tagging you since you have worked on the filter class method related to xarray datasets. 😃) I think this only requires some minor fixes.

**Comment by asross** [comment]
@NoraLoose sure, sounds good. Maybe the simplest fix is just to make `apply_to_field` a private method (which we just do by adding an `_` to its name? is that the convention?). Let me know if that makes sense.

**Comment by asross** [comment]
We could also merge them into a single `apply` function that recursively calls itself, I guess!

**Comment by NoraLoose** [comment]
> Maybe the simplest fix is just to make apply_to_field a private method (which we just do by adding an _ to its name? is that the convention?). 

Making the method private (via a `_` prefix) sounds good to me. That's what we did in other places, for example [here](https://github.com/ocean-eddy-cpt/gcm-filters/blob/7dfd3fef4bacb912ae04cb1fadf3fcc839aba881/gcm_filters/kernels.py#L32-L33) or [here](https://github.com/ocean-eddy-cpt/gcm-filters/blob/7dfd3fef4bacb912ae04cb1fadf3fcc839aba881/gcm_filters/filter.py#L46).

**Comment by asross** [comment]
Awesome, created a PR!
