### ISSUE TITLE
Binder link

### ISSUE THREAD

**Issue by NoraLoose** [ocean-eddy-cpt/gcm-filters#112]
As [suggested](https://github.com/ocean-eddy-cpt/gcm-filters/pull/109#issuecomment-991032830) by @rabernat, we could create a binder link on the repo that opens the example notebooks.

**Comment by rabernat** [comment]
Let's see how this works:

https://mybinder.org/v2/gh/pangeo-data//2021.12.02?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Focean-eddy-cpt%252Fgcm-filters%252F%26urlpath%3Dlab%252Ftree%252F%252Fdocs%252Fexamples%26branch%3Dmaster

(via https://jupyterhub.github.io/nbgitpuller/link)
