### ISSUE TITLE
License and description do not update on conda-forge

### ISSUE THREAD

**Issue by NoraLoose** [ocean-eddy-cpt/gcm-filters#117]
A while ago, I tried to update license and description of GCM-Filters on [conda-forge](https://anaconda.org/conda-forge/gcm_filters) but unsuccessfully. I opened an [issue on the gcm_filters-feedstock](https://github.com/conda-forge/gcm_filters-feedstock/issues/3) and asked for help on conda Gitter but haven't been able to solve the issue yet. Does anyone here have ideas for what to do? 

cc @rabernat and @jbusecke

**Comment by NoraLoose** [comment]
The problem persists. 

I just merged https://github.com/conda-forge/gcm_filters-feedstock/pull/6 on the conda-forge feedstock, and replaced the old license `BSD-3-Clause` by `LGPL-3.0`. Nevertheless, it did not get deployed correctly, and users who download gcm-filters from [conda](https://anaconda.org/conda-forge/gcm_filters) get told that the license is still `BSD-3-Clause`.

**Comment by iangrooms** [comment]
conda-forge currently says LGPL-3.0, so closing this issue.
