### ISSUE TITLE
add environment file/ extra dependencies for example notebooks

### ISSUE THREAD

**Issue by isgiddy** [ocean-eddy-cpt/gcm-filters#118]
I was running through the documentation file examples - which are really great! and needed to install dependencies along the way. I noticed there was an environment file in the docs folder but think this is not for running the individual notebooks, but rather compiling the documentation?

For users who might want to do what I did, it could be nice to state these extra dependencies (beyond numpy, xarray and dask) /provide an environment file to run through the examples.

Listing them here for reference:
matplotlib
cupy (optional)
intake
intake-xarray
s3fs
cartopy

**Comment by NoraLoose** [comment]
Thanks for pointing out this issue, @isgiddy! I just opened a PR (#120) that should solve this for the user.

I'm also tagging our [JOSS review thread](https://github.com/openjournals/joss-reviews/issues/3947) so we can keep track over there of which issues are open / closed.
