### ISSUE TITLE
docs: make links open in a new tab

### ISSUE THREAD

**Issue by isgiddy** [ocean-eddy-cpt/gcm-filters#119]
this is totally optional

you can replace the markdown link syntax with this html so that the links open in a new tab

`[Murray, 1996](https://www.sciencedirect.com/science/article/pii/S0021999196901369)`

`<a href="https://www.sciencedirect.com/science/article/pii/S0021999196901369" target="_blank">Murray, 1996</a>`

**Comment by rabernat** [comment]
Thanks for the suggestion @isgiddy!

My opinion is that having links open in new tabs is not worth the cost of having to write all our links in HTML rather than markdown.

**Comment by isgiddy** [comment]
I agree. Think this is a feature for future markdown code :)
