### ISSUE TITLE
Can I be added to the org

### ISSUE THREAD

**Issue by jbusecke** [ocean-eddy-cpt/gcm-filters#12]
Hi @NoraLoose, could you add me as a member of the organization? 

I am hitting some snags over at #11 and was wondering if I could set up the Readthedocs integration via the `ocean-eddy-cpt` organization.

**Comment by rabernat** [comment]
Unfortunately we cannot do that without formal approval from the CPT executive council. There are lots of private repos here.

Let's figure out a way that doesn't require org-level permissions. Or tell me what to do and I can do it.

**Comment by jbusecke** [comment]
Got it. Perhaps somebody of the org could create the RTD project and make me a co-maintainer there?

**Comment by rabernat** [comment]
Ok, I think I got it to work: https://readthedocs.org/dashboard/gcm-filters/edit/
