### ISSUE TITLE
[BUG] Error in commutation grows drammatically with filter scale.

### ISSUE THREAD

**Issue by dhruvbalwada** [ocean-eddy-cpt/gcm-filters#135]
One property of the filter is that it should commute with gradients. This is satisfied by gcm-filters when the filter scale is small, but as the scale increases, this condition breaks very dramatically (see figure below). I am on a simple cartesian grid.

Here is a notebook where I tested this on a simulation: https://gist.github.com/dhruvbalwada/0d2a6541cf584502401e8b6bfe0b325b 
This is not a reproducible example, but I think it presents the case easily enough. 

Here I compare the gcm-filters against a regular gaussian convolution filter from [scipy](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.filters.gaussian_filter.html). 

The figure below shows the impact of two different filters on commutation and sum properties as a function of filter scale. While the choice of method does not impact the preservation of the sum (right plot), but the commutation with an x-gradient gets worse with filter scale for gcm-filters (left plot). 
![Screen Shot 2022-02-07 at 10 52 54 AM](https://user-images.githubusercontent.com/18236610/152823454-392ce7f0-fc4b-4081-9d4c-e1f89522a483.png)

Note that the issue becomes quite bad even for filter scales of 80-100km in a 5km resolution run, suggesting that it would be hard to correctly filter out mesoscale eddies in mesoscale permitting simulation - an important base case for gcm-filters.

In the notebook I also plot the impact of the different filters on the spectra (below cell [13]), and it seems that for larger filters scales the gcm-filters does not filter at the grid scale. This grid scale variance (or noise) is the likely culprit for breakdown of the filter-commutation property. 

@rabernat mentioned that there might be a solution to this coming through soon, and that I should highlight this in an issue.

**Comment by dhruvbalwada** [comment]
Maybe #134 will fix this - @NoraLoose ?

**Comment by iangrooms** [comment]
OK, glad it's working better for you now. Closing this because I don't think it's a bug.

**Comment by NoraLoose** [comment]
Hi @dhruvbalwada, thanks for trying and testing GCM-Filters!

> I am not sure how to do the factoring of the Gaussian that you mentioned.

The factoring of the Gaussian is described [here](https://gcm-filters.readthedocs.io/en/latest/factored_gaussian.html) and in [this example](https://gcm-filters.readthedocs.io/en/latest/examples/example_numerical_instability.html).

Please let us know if you have other issues or questions, and I will reopen this issue.
