### ISSUE TITLE
how to use gcm-filter to bandpass filter ？

### ISSUE THREAD

**Issue by xpji** [ocean-eddy-cpt/gcm-filters#152]
1、How to use `gcm-filter` to bandpass filter in three-dimensional data?
such as ： wind speed component：u、v
2、Whether to make the consideration of equal spacing.
3、How to set those parameters？
4、 how to simply understand the data variables corresponding to the parameters

**Comment by NoraLoose** [comment]
Hi @xpji!

Re 1:  

- **Number of dimensions**: `GCM-Filters` can be applied to three- (or four-) dimensional data, see for example [here](https://gcm-filters.readthedocs.io/en/latest/basic_filtering.html#applying-the-filter). But the filter operates over two dimensions *only*, which have to specified when applying the filter: `filter.apply(da_masked, dims=['y', 'x'])`
- **Band-pass filtering**:
`GCM-Filters` is for low-pass filtering. If you want to create a band-pass filter, you can do this by using and combining `GCM-Filters` with different filter scales, see for example Equation (7) in @jakesteinberg's paper [Steinberg et al., 2022](https://www.essoar.org/doi/abs/10.1002/essoar.10508837.1).

Re 2 - 4: [Here](https://gcm-filters.readthedocs.io/en/latest/examples/example_filter_types.html) you can find examples for how to apply filters with equal filter scales in x- and y-direction. 

Please let us know if you have further questions!

**Comment by NoraLoose** [comment]
I'm closing this issue because it has been stalled for more than a year.
