### ISSUE TITLE
Tests are failing due to zarr-related(?) module import

### ISSUE THREAD

**Issue by NoraLoose** [ocean-eddy-cpt/gcm-filters#156]
Since 2 days ago, our tests are suddenly failing with a module import error, potentially related to zarr:
```
tests/test_kernels_validation.py:6: in <module>
    import zarr
/usr/share/miniconda/envs/gcm-filters-env/lib/pypy3.9/site-packages/zarr/__init__.py:2: in <module>
    from zarr.codecs import *
/usr/share/miniconda/envs/gcm-filters-env/lib/pypy3.9/site-packages/zarr/codecs.py:2: in <module>
    from numcodecs import *
/usr/share/miniconda/envs/gcm-filters-env/lib/pypy3.9/site-packages/numcodecs/__init__.py:100: in <module>
    from numcodecs.shuffle import Shuffle
/usr/share/miniconda/envs/gcm-filters-env/lib/pypy3.9/site-packages/numcodecs/shuffle.py:4: in <module>
    from ._shuffle import _doShuffle, _doUnshuffle
E   ModuleNotFoundError: No module named 'numcodecs._shuffle'
```

Any ideas what is going on @rabernat @jbusecke @paigem @pbranson?

**Comment by pbranson** [comment]
I wonder if this has something related to the discussion here: https://github.com/fsspec/kerchunk/issues/195 

It seems like it is possibly something is wrong with the build of numcodecs in your test environment.

**Comment by pbranson** [comment]
Its weird as you are using the conda-forge release of numcodecs which should have Shuffle.

**Comment by pbranson** [comment]
Looks like there was a new of numcodecs a couple of weeks ago - maybe try pinning the version of numcodecs back and see if it resolves.

**Comment by NoraLoose** [comment]
@pbranson thanks for these pointers!

> maybe try pinning the version of numcodecs back and see if it resolves

Will try ☝️

**Comment by rabernat** [comment]
Thanks @pbranson for opening the upstream issue so this can get fixed at the source!
