### ISSUE TITLE
ValueError while trying to filter with fixed factor, using MOM5

### ISSUE THREAD

**Issue by marimpacheco** [ocean-eddy-cpt/gcm-filters#162]
Hi,

I want to use gcm-filters to filter a lat/lon(3S-46S/132W-68W) section of the GFDL CM2.6 model (MOM5, 0.1°) using a filter with fixed factor (spatially-varying and anisotropic filter), and with a 15° longitude, 5° latitude cut-off wavelength. I want to filter tracers (temp, o2, ph). 

Since MOM5 is NE-oriented, I selected the dxu, dxt, dyu and dyt accordingly so dxu would be located southwest of dxt (not sure if that is necessary? or a wrong way to proceed?).

Then I followed all the steps in the [example](https://gcm-filters.readthedocs.io/en/latest/examples/example_filter_types.html#filtering-with-a-fixed-factor) and choosing as filter scale:

```python
dx_max = max(dxu.max(),dyu.max(),dxt.max(),dyt.max())
dx_max = dx_max.values

filter_scale = 150 * dx_max # 15 degrees in longitude; each cell is 0.1 degree
kappa_w = dxt * dxt / (dx_max * dx_max)
kappa_s =  (1/900) * dyt * dyt / (dx_max * dx_max) # 5 degrees in latitude

filter_fixed_factor = gcm_filters.Filter(
    filter_scale=filter_scale,
    dx_min=dx_min,
    filter_shape=gcm_filters.FilterShape.GAUSSIAN,
    grid_type=gcm_filters.GridType.IRREGULAR_WITH_LAND,
    grid_vars={
        'wet_mask': wet_mask, 
        'dxw': dxt, 'dyw': dyt, 'dxs': dxu, 'dys': dyu, 'area': area, 
        'kappa_w': kappa_w, 'kappa_s': kappa_s
    }
)
filter_fixed_factor
```
```
Filter(filter_scale=1665563.4834155159, dx_min=array(7591.0808314), filter_shape=<FilterShape.GAUSSIAN: 1>, transition_width=3.141592653589793, ndim=2, n_steps=242, grid_type=<GridType.IRREGULAR_WITH_LAND: 5>)
```

However, when I try to run the filtering, I get the error: ValueError: At least one place in the domain must have either kappa_w = 1.0 or kappa_s = 1.Otherwise the filter's scale will not be equal to filter_scale anywhere in the domain.

But:
```python
kappa_w.max()
```
```
1
```
If I add the `(1/900) *` to the kappa_s and remove it from kappa_w, it works.

How should I solve this? Thanks!

**Comment by NoraLoose** [comment]
Hi @marimpacheco, thanks for reaching out! I think I came across the same problem a while ago, which is why I opened PR #161. Let's merge the PR and see if this solves your problem.

**Comment by marimpacheco** [comment]
Hi Nora, I reinstalled gcm-filters, but unfortunately the problem remains

**Comment by iangrooms** [comment]
@marimpacheco did you install directly from the website? The changes have not been pushed to conda or pip yet, so if you re-installed from there you wouldn't have gotten the updates

**Comment by marimpacheco** [comment]
Ah right, from the commit it works, thanks!

**Comment by marimpacheco** [comment]
Hi, I have a question on how to adjust the dxw/dyw/dxs/dys values using MOM5 with the `grid_type=gcm_filters.GridType.IRREGULAR_WITH_LAND`, since I think I was taking the wrong approach. 

In issue #24 @NoraLoose mentioned we should set:
`dxw =  0.5 * (np.roll(dxt, 1, axis=1) + np.roll(np.roll(dxt, 1, axis=1), 1, axis=0)),` and similarly for dyw, dxs, dys (assuming that your coordinates have the order (j,i)).
I assume the same equation applies to dyw, dyt, but I am not sure for dxs and dys.
Is that something like:
 `dxs = 0.5 * ( dxu + np.roll(dxu, -1, axis=0))` ?
Thanks!

**Comment by marimpacheco** [comment]
I need to use the IRREGULAR_WITH_LAND in order to use a fixed factor filter. `gcm_filters.GridType.MOM5T` and `gcm_filters.GridType.MOM5U` do not have kappa_w and kappa_s. Or is there another way?

**Comment by NoraLoose** [comment]
Another (easier) option is to use a simple fixed factor filter with `REGULAR_WITH_LAND_AREA_WEIGHTED`. This grid type only requires grid variables that should be directly available from the MOM5 output.

https://gcm-filters.readthedocs.io/en/latest/examples/example_filter_types.html#simple-fixed-factor-filter

**Comment by iangrooms** [comment]
@marimpacheco did xgcm resolve your problem? Can we close this issue?

**Comment by marimpacheco** [comment]
Yes, it did, thanks :)
