### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by NoraLoose** [ocean-eddy-cpt/gcm-filters#163]
There seems to be an issue with conda? 

https://github.com/ocean-eddy-cpt/gcm-filters/actions/runs/6930660764/job/18850752922#step:4:2180

@jbusecke do you know what is going on?

**Comment by jbusecke** [comment]
Short answer: Not really. 

**BUT** I believe I have encountered this before and it was fixable by using micromamba. See for example the changes made in [xgcm](https://github.com/xgcm/xgcm/commit/0a130d1e4974de70f877b6abd80934ae019a3c00)

**Comment by jbusecke** [comment]
Ok I started #164, but saw that we only deal with [pip requirements here](https://github.com/ocean-eddy-cpt/gcm-filters/blob/master/requirements.txt)? Why are we even using mamba/conda at all?

**Comment by NoraLoose** [comment]
Thanks @jbusecke! I am confused about this, too. You set up the testing framework originally, so I trusted you on this. ;)

I think we want to use conda [to make contributions easier and the notebooks reproducible by users](https://gcm-filters.readthedocs.io/en/latest/how_to_contribute.html). But your question might be separate from this, namely whether we need conda for the testing framework?
