### ISSUE TITLE
Define options for boundaries

### ISSUE THREAD

**Issue by rabernat** [ocean-eddy-cpt/gcm-filters#2]
There are several different ways to handle boundaries:

- Just ignore the presence of boundaries, put a fill value in the land mask, and allow the diffusion to smooth it. This is actually what Aluie recommends, as it preserves the commutation properties of the smoothing operator. It might make sense for u / v (reasonable to set to zero in land), but is more problematic for tracers. 
- Use a conservative boundary condition (e.g. no flux), as the GCM would, on the boundaries.

It would be nice to support both options, allowing us to experiment. However, the two kernels are different. The former doesn't need any information about the land mask, while the latter does.

**Comment by rabernat** [comment]
This is closely related to the API design question (#4).

**Comment by rabernat** [comment]
@NoraLoose is using the second option when analyzing MOM6.

**Comment by iangrooms** [comment]
It would be nice to support both, but I guess it means we'll have two different kernels for each grid: one that ignores boundaries and is faster, and another that uses a land mask to take boundaries into account. One question I have is whether the kernel with boundaries will really be slower. On non-uniform grids the kernel is different at every grid point, so wouldn't that be basically the same as having a kernel that knows about land?

**Comment by NoraLoose** [comment]
@iangrooms, for a filter with fixed coarsening factor relative to the local grid scale, the kernel respecting boundaries is cell 16 in [this notebook](https://github.com/ocean-eddy-cpt/spatial-filtering/blob/main/NW2_EKE_budget.ipynb). Compare to the kernel that ignores boundaries in cell 3 of [Ryan's notebook](https://nbviewer.jupyter.org/gist/rabernat/429238a9db40fb3dbfc74b84f64a4b36#). Since the boundary-aware kernel has to compute an additional factor (referred to as c in my notebook) based on the land mask, I think it will be slower - but we can/should test this. 

Kernels only differ from grid point to grid point for filters with fixed filter scale (rather than fixed filter factor).

**Comment by rabernat** [comment]
I am probably using the term kernel in a different (wrong) way here. For the purposes of this package, a kernel is a python function that takes a 2D field and returns the laplacian. It's not necessarily a "stencil" in the standard computational sense.

What matters is, what is the function signature, i.e. what arrays are needed in order to compute the laplacian. The example kernel only has a single input `phi`, the scalar to diffuse:

https://github.com/ocean-eddy-cpt/gcm-filters/blob/09ed575b9c2e595c1e4914368c63138e7cf59d68/gcm_filters/kernels.py#L17-L18

However, we might imagine that a curvilinear grid might also require some metric arrays, e.g.
```python
curvilinear_laplacian(phi, dx, dy, area):
```

A kernel with land would require a land mask to be input.
```python
curvilinear_laplacian(phi, dx, dy, area, land_mask):
```

etc.

These kernel functions will probably look different for the different models, depending on their numerics.

> One question I have is whether the kernel with boundaries will really be slower.

This is a good question, and we should test it. At minimum, we know it will have a higher memory footprint, because it has to keep track of an additional array (`land_mask`).

**Comment by jbusecke** [comment]
> These kernel functions will probably look different for the different models, depending on their numerics.

Will the logic for handling boundaries also differ? Just trying to imaging an overall structure for the package, and how we could factor out common logic from each kernel.
