### ISSUE TITLE
Agree on API for how we want to use this package

### ISSUE THREAD

**Issue by rabernat** [ocean-eddy-cpt/gcm-filters#4]
How will users interact with the gcm-filters package? We can answer this a bit by looking at existing code by @NoraLoose.

I image something like this (pseudocode)

```python
from gcm_filters import Filter

filter = Filter(scale=100_000., other_param=3, model="mom6", grid=grid_object)
scalar_filtered = filter.apply_scalar(scalar)
u_filt, v_filt = filter.apply_vector(u, v)
```

Answering this requires us to determine what are the input parameters to the filter design algorithm.

**Comment by rabernat** [comment]
What about "bring your own kernel"? BYOK.

**Comment by rabernat** [comment]
What about

```python
Filter(kernel="mom6")
````

or 
```python
Filter(kernel=my_custom_kernel)
```

**Comment by iangrooms** [comment]
I like BYOK. The package can provide whatever kernels we write (e.g. POP for the paper?). If a user wants to use this for something new then they just have to write a Laplacian kernel for their grid, and we can encourage them to submit it as a pull request so we can add it to the package.
