### ISSUE TITLE
Contribution and authorship

### ISSUE THREAD

**Issue by jbusecke** [ocean-eddy-cpt/gcm-filters#44]
We should compile a list of authors for the paper. 

What criteria are we using? A straightforward choice would be to say everyone who has submitted any code to the repo is on the paper. Let me know what you think.

**Comment by arthurBarthe** [comment]
Thanks @NoraLoose. My details are:
Courant Institute of Mathematical Sciences, New York University, New York, NY 10012, USA
ORCID: 0000-0003-1571-4228

Thanks @LaureZanna  and @ElizabethYankovsky for transfering the email :)
