### ISSUE TITLE
The actual JOSS paper

### ISSUE THREAD

**Issue by jbusecke** [ocean-eddy-cpt/gcm-filters#47]
@NoraLoose will lead the actual writing of the paper. 

I will just post a checklist here for completeness:

- [x] Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] A statement of need: Does the paper have a section titled ‘Statement of Need’ that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] State of the field: Do the authors describe how this software compares to other commonly-used packages?
- [ ] Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper citation syntax?

**Comment by NoraLoose** [comment]
Thanks @jbusecke for posting this checklist - very useful!
