### ISSUE TITLE
zenodo DOI

### ISSUE THREAD

**Issue by jbusecke** [ocean-eddy-cpt/gcm-filters#51]
Should I set up a [zenodo](https://zenodo.org) DOI for the package in addition to the one we will get from the JOSS paper? 

This will be updated with every release, and I think it is a good addition to have.

**Comment by rabernat** [comment]
Zenodo now requires a [CITATION.cff](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files) file for the integration to work.

**Comment by NoraLoose** [comment]
@jbusecke is this something we should figure out before submitting the JOSS paper?

**Comment by rabernat** [comment]
IMO Zenodo is not as important if we are going the JOSS route.

**Comment by jbusecke** [comment]
Ah sorry I totally missed this. I am happy to set this up, but I concur with ryan that the JOSS paper is probably the avenue we want to get our citations through.
