### ISSUE TITLE
Tutorial on filtering data on tripole grid 

### ISSUE THREAD

**Issue by NoraLoose** [ocean-eddy-cpt/gcm-filters#53]
Show how the use of different Laplacians will
* **ignore** tripolar exchanges (`REGULAR_WITH_LAND` & `IRREGULAR_WITH_LAND`)
* **handle** tripolar exchanges (`TripolarRegularLaplacianTpoint` & `POPTripolarLaplacianTpoint`)

**Comment by jbusecke** [comment]
Should I make this part of the JOSS project?
