### ISSUE TITLE
Publish action should not run on push?

### ISSUE THREAD

**Issue by jbusecke** [ocean-eddy-cpt/gcm-filters#55]
I just noticed that the [publishing github action](https://github.com/ocean-eddy-cpt/gcm-filters/actions/workflows/publish-to-pypi.yml) runs on every [push event](https://github.com/ocean-eddy-cpt/gcm-filters/blob/f3f644a3b291f8ee0b5348b47aa74f14e80af0a9/.github/workflows/publish-to-pypi.yml#L3). 

Is this intentional? I usually set this to be only triggered by a release.

@rabernat should I change this?

**Comment by rabernat** [comment]
Yes I think you should change it. Thanks Julius!

**Comment by jbusecke** [comment]
Actually it seems like the upload does only happen for tagged versions (I overlooked this before), so I think there is actually no harm in building the distro for each push. Ill close this.
