### ISSUE TITLE
create documentation stub

### ISSUE THREAD

**Issue by rabernat** [ocean-eddy-cpt/gcm-filters#7]
We need to set up a simple sphinx documentation site and set it up to build automatically with readthedocs.

@jbusecke, I will assign this to you once you accept the invite to join this repo.

**Comment by jbusecke** [comment]
Done. I'll get to it in a bit.

**Comment by jbusecke** [comment]
I am having trouble registering the repo with RTD. Could you promote me to maintainer?

**Comment by rabernat** [comment]
You were maintainer. Now you are admin. Thx!

**Comment by jbusecke** [comment]
None of that worked. I think this might be some bug, because I imported the project to rtd manually. Not sure what the proper way to set this up is. Should I be part of the ocean-eddy-cpt org? Can you check if you can automatically add gcm-filters in your RTD account? I only see my fork!

**Comment by rabernat** [comment]
Hmmm. Maybe look closely at xgcm and try to identify what is different.

**Comment by jbusecke** [comment]
Can you make me a maintainer over at https://readthedocs.org/projects/xgcm/ (username:`jbusecke`)?
