### ISSUE TITLE
Add MOM5 kernel

### ISSUE THREAD

**Issue by rabernat** [ocean-eddy-cpt/gcm-filters#8]
cc @LaureZanna, as discussed on Slack

**Comment by rabernat** [comment]
The package is ready to have laplacians added to it. They should be added to this file:

https://github.com/ocean-eddy-cpt/gcm-filters/blob/master/gcm_filters/kernels.py

There are three things that need to be added in that file:
1. A new class (e.g. `MOM5Laplacian`), which inherits from `BaseLaplacian`. Any auxiliary grid variables (e.g. tarea, dx, dy, etc.) should be attributes of the class. The actual laplacian should be coded in the `__call__` method and have only a single argument.
2. Define a new `GridType` here:
   https://github.com/ocean-eddy-cpt/gcm-filters/blob/91cd5794e1518e5631600b3590e173973c140291/gcm_filters/kernels.py#L14
   Maybe something like `MOM_GRID`
3. Then add the laplacian to the `ALL_KERNELS` dictionary, like this
   https://github.com/ocean-eddy-cpt/gcm-filters/blob/91cd5794e1518e5631600b3590e173973c140291/gcm_filters/kernels.py#L14

Then the kernel will automatically get tested in the `test_kernels.py` module.
However, it probably won't work unless you define special options for the grid_vars, as here
https://github.com/ocean-eddy-cpt/gcm-filters/blob/91cd5794e1518e5631600b3590e173973c140291/tests/test_kernels.py#L15-L18

For the tests, we will need to decide about #5. I have some ideas about that I'll share in that issue.

cc @LaureZanna

**Comment by rabernat** [comment]
@jbusecke maybe you could give a quick overview of the development process

- running tests locally
- pre-commit
- docstrings

**Comment by ElizabethYankovsky** [comment]
@rabernat - Thanks for cc-ing! Laure, her postdoc Arthur, and I have been discussing the formulation of the Laplacian in MOM5 and will contribute to this

**Comment by jbusecke** [comment]
Sure thing. Where should that go? As a docs page?

**Comment by rabernat** [comment]
> Sure thing. Where should that go? As a docs page?

I was thinking just a comment on github, but a contributor guide on the docs is probably more robust. Could probably just be copy-pasted from one of our other projects.

**Comment by jbusecke** [comment]
How detailed should this be with regard to git? Full step by step with add/commit/...?

**Comment by jbusecke** [comment]
Take a look at my PR #16

**Comment by LaureZanna** [comment]
Thanks a lot @rabernat and @jbusecke !

**Comment by iangrooms** [comment]
I think our scalar Laplacians work for MOM5, and #106 is developing a vector Laplacian that should work for MOM5. Can we close this issue?
