### ISSUE TITLE
conda packaging

### ISSUE THREAD

**Issue by aidanheerdegen** [ocean-eddy-cpt/gcm-filters#81]
Is there any interest or indeed plans to add conda packaging through your own channel or conda-forge?

**Comment by rabernat** [comment]
Yes definitely! Just have not gotten around to it yet. Since we are currently a pure-python package, pip works pretty well in the interim.

If you are interested in helping out and creating a conda feedstock for gcm-filters, please go right ahead, and add myself and @NoraLoose as maintainers.

**Comment by rabernat** [comment]
In progress at https://github.com/conda-forge/staged-recipes/pull/16108

**Comment by aidanheerdegen** [comment]
Thanks, and sorry not to have done it earlier.
