### ISSUE TITLE
Helper method for applying a filter to an xarray Dataset

### ISSUE THREAD

**Issue by asross** [ocean-eddy-cpt/gcm-filters#89]
I've found myself writing a wrapper method around `Filter#apply` that works for both `DataArray`s and `Dataset`s (applying to all variables that have the given `dims`):

```python
def apply(filter, ds, dims=['y','x']): 
    if isinstance(ds, xr.Dataset):
        filtered = ds.copy()
        for k, v in ds.variables.items():
            if all(d in v.dims for d in dims):
                filtered[k] = filter.apply(ds[k], dims=dims)
        return filtered
    else:
        return filter.apply(ds, dims=dims)
```

Would it make sense to make a PR that wraps the [current definition of `Filter#apply`](https://github.com/ocean-eddy-cpt/gcm-filters/blob/master/gcm_filters/filter.py#L414) with a helper of this kind?

**Comment by rabernat** [comment]
Yes, I think this would be a very useful contribution. Thanks a lot for your offer!

Please make sure to include tests for any new features you propose in your PR.

**Comment by asross** [comment]
Awesome! I created a PR :)
